language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - rm -rf /test/coverage
